### ISSUE TITLE
Can not import after configuring Oauth

### ISSUE THREAD

**Issue by jbjanot** [matomo-org/plugin-GoogleAnalyticsImporter#251]
Hi Matomo team!

I went through all the process of creating an Oauth id to import my Google Analytics data to Matomo, in the WordPress environment.
It seems to work fine, I was able to approve the connexion with my Google Account.
However, once the approval has been made, the scheduler import is blank, and I have console errors.
Specifically, here is the error I am seeing :

```
Uncaught Error: Unknown plugin in vue-entry: GoogleAnalyticsImporter.ImportScheduler
    at HTMLDivElement.<anonymous> (asset_manager_core_js.js?v=4.10.0?cb=e78b0f73f9fa91c94c120b5df04135d7:777:153)
    at Function.each (jquery.js?cb=e78b0f73f9fa91c94c120b5df04135d7:385:19)
    at jQuery.fn.init.each (jquery.js?cb=e78b0f73f9fa91c94c120b5df04135d7:207:17)
    at Object.compileVueEntryComponents (asset_manager_core_js.js?v=4.10.0?cb=e78b0f73f9fa91c94c120b5df04135d7:775:66)
    at HTMLDocument.<anonymous> (asset_manager_core_js.js?v=4.10.0?cb=e78b0f73f9fa91c94c120b5df04135d7:820:258)
    at mightThrow (jquery.js?cb=e78b0f73f9fa91c94c120b5df04135d7:3766:29)
    at process (jquery.js?cb=e78b0f73f9fa91c94c120b5df04135d7:3834:12)
```

There is also some errors with a manifest.json file : 

```
Failed to load resource: the server responded with a status of 403 ()
Manifest: Line: 1, column: 1, Syntax error.
Failed to load resource: the server responded with a status of 403 ()
```

Thank you very much for your help!

**Comment by mattmary** [comment]
Hi team,

others users seem to be affected too
https://wordpress.org/support/topic/import-google-analytics-scheduler-stay-empty/#post-15737318

**Comment by AltamashShaikh** [comment]
This is more of a issue with core not with the plugin, https://github.com/matomo-org/matomo/pull/19362 should fix the issue

**Comment by Starker3** [comment]
FYI this happened in a standard install when testing the GA4 branch:
![image](https://user-images.githubusercontent.com/20905821/174218388-a1a5de09-6b9b-4498-9187-4e1ace28f059.png)

Applying the patched file from https://github.com/matomo-org/matomo/pull/19362 resolved the issue

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/schedule-an-import-is-not-showing-google-analytics-importer/46361/2

**Comment by magicmax1967** [comment]
Hello, same issue here. [Fix #19362](https://github.com/matomo-org/matomo/pull/19362) does not resolve for me.

**Comment by AltamashShaikh** [comment]
@magicmax1967 Do you get any error in console ?
If yes can you paste the screenshot of that here ?

**Comment by madeincima** [comment]
Same issue here.

We have the error "Uncaught Error: Unknown plugin in vue-entry: GoogleAnalyticsImporter.ImportScheduler" in "asset_manager_core_js.js:777:153"

**Comment by AltamashShaikh** [comment]
Hello everyone, we have Just release Matomo 4.11 and hopefully soon will have a Matomo 4.11 for wordpress, which will fix this issue.

**Comment by AltamashShaikh** [comment]
@jbjanot Should we close this issue ?

**Comment by jbjanot** [comment]
@AltamashShaikh Yes, the issue is fixed in the latest version of the plugin. Thank you for your help!
