### ISSUE TITLE
Impossible to relance import

### ISSUE THREAD

**Issue by pdechanoz** [matomo-org/plugin-GoogleAnalyticsImporter#274]
Impossible to relance import  : (Entry #0) is finished, moving on.

 What can I do ?

Logfile : 

Running archiving for newly imported data...
INFO [2022-09-17 00:06:18] 2051792  ---------------------------
INFO [2022-09-17 00:06:18] 2051792  INIT
INFO [2022-09-17 00:06:18] 2051792  Running Matomo 4.11.0 as Super User
INFO [2022-09-17 00:06:18] 2051792  ---------------------------
INFO [2022-09-17 00:06:18] 2051792  NOTES
INFO [2022-09-17 00:06:18] 2051792  - Async process archiving supported, using CliMulti.
INFO [2022-09-17 00:06:18] 2051792  - Reports for today will be processed at most every 900 seconds. You can change this value in Matomo UI > Settings > General Settings.
INFO [2022-09-17 00:06:18] 2051792  - Archiving was last executed without error 59s ago.
INFO [2022-09-17 00:06:18] 2051792  - Will process 1 websites (--force-idsites)
INFO [2022-09-17 00:06:18] 2051792  - Will process specified sites: 5
INFO [2022-09-17 00:06:18] 2051792  - Will only process the following periods: week, month, year (--force-periods)
INFO [2022-09-17 00:06:18] 2051792  ---------------------------
INFO [2022-09-17 00:06:18] 2051792  START
INFO [2022-09-17 00:06:18] 2051792  Starting Matomo reports archiving...
INFO [2022-09-17 00:06:18] 2051792  Start processing archives for site 5.
INFO [2022-09-17 00:06:18] 2051792    Will invalidate archived reports for today in site ID = 5's timezone (2022-09-17 00:00:00).
INFO [2022-09-17 00:06:18] 2051792    Will invalidate archived reports for yesterday in site ID = 5's timezone (2022-09-16 00:00:00).
INFO [2022-09-17 00:06:20] 2051792  Archived website id 5, period = week, date = 2022-09-12, segment = '', 72080 visits found. Time elapsed: 1.649s
INFO [2022-09-17 00:06:21] 2051792  Archived website id 5, period = month, date = 2022-09-01, segment = '', 201691 visits found. Time elapsed: 1.713s
INFO [2022-09-17 00:06:24] 2051792  Archived website id 5, period = year, date = 2022-01-01, segment = '', 1915445 visits found. Time elapsed: 2.568s
INFO [2022-09-17 00:06:24] 2051792  Finished archiving for site 5, 3 API requests, Time elapsed: 6.128s [1 / 1 done]
INFO [2022-09-17 00:06:24] 2051792  Done archiving!
INFO [2022-09-17 00:06:24] 2051792  ---------------------------
INFO [2022-09-17 00:06:24] 2051792  SUMMARY
INFO [2022-09-17 00:06:24] 2051792  Processed 3 archives.
INFO [2022-09-17 00:06:24] 2051792  Total API requests: 3
INFO [2022-09-17 00:06:24] 2051792  done: 3 req, 6131 ms, no error
INFO [2022-09-17 00:06:24] 2051792  Time elapsed: 6.131s
INFO [2022-09-17 00:06:24] 2051792  ---------------------------
INFO [2022-09-17 00:06:24] 2051792  SCHEDULED TASKS
INFO [2022-09-17 00:06:24] 2051792  Scheduled tasks are disabled with --disable-scheduled-tasks
Done in Time elapsed: 65.046s. [40 API requests made to GA]
Error: error or warning logs detected, exit 1
Resuming import into existing site 5.
INFO [2022-09-17 01:05:16] 2073216  Using existing custom variable slots.
Importing the following date ranges in order: 2021-06-01,2022-09-16
(Entry #0) is finished, moving on.
Done in Time elapsed: 0.527s. [0 API requests made to GA]
Resuming import into existing site 5.
INFO [2022-09-17 02:05:17] 2097175  Using existing custom variable slots.
Importing the following date ranges in order: 2021-06-01,2022-09-16
(Entry #0) is finished, moving on.
Done in Time elapsed: 0.495s. [0 API requests made to GA]
Resuming import into existing site 5.

**Comment by snake14** [comment]
Hi @pdechanoz . Thank you for taking the time to create an issue. Thank you for providing the log data. I'm still not quite sure which exact issue you are trying to address. Could you please provide a bit more context? @AltamashShaikh can you tell what's going wrong?

**Comment by AltamashShaikh** [comment]
@pdechanoz Can you run a new import and enable verbose logging ?
It will create a log file in `/path/to/your/matomo/tmp/logs/gaimportlog.{idSite}..log` and you can share that file which will help us in debugging the issue

**Comment by pdechanoz** [comment]
I have relaunched with a new idiSite : 

logfile (gaimportlog.6..log  total = 2914 lines )


line 2813 to end :

WARNING [2022-09-19 04:18:12] 3740682  Encountered unknown browser: YaBrowser. A new mapping should be added.
WARNING [2022-09-19 04:18:12] 3740682  Encountered unknown browser: YaBrowser. A new mapping should be added.
WARNING [2022-09-19 04:18:12] 3740682  Encountered unknown browser: YaBrowser. A new mapping should be added.
WARNING [2022-09-19 04:18:12] 3740682  Encountered unknown browser: YaBrowser. A new mapping should be added.
WARNING [2022-09-19 04:18:12] 3740682  Encountered unknown browser: YaBrowser. A new mapping should be added.
WARNING [2022-09-19 04:18:12] 3740682  Encountered unknown browser: YaBrowser. A new mapping should be added.
WARNING [2022-09-19 04:18:12] 3740682  Encountered unknown browser: YaBrowser. A new mapping should be added.
WARNING [2022-09-19 04:18:12] 3740682  Encountered unknown browser: YaBrowser. A new mapping should be added.
WARNING [2022-09-19 04:18:12] 3740682  Encountered unknown browser: YaBrowser. A new mapping should be added.
INFO [2022-09-19 04:18:18] 3740682  Importing data for GA View 81857407 for date 2022-05-16...
WARNING [2022-09-19 04:18:20] 3740682  Encountered unknown search engine source from Google Analytics: qwant.com
WARNING [2022-09-19 04:18:20] 3740682  Encountered unknown search engine source from Google Analytics: ecosia.org
WARNING [2022-09-19 04:18:20] 3740682  Encountered unknown search engine source from Google Analytics: go.mail.ru
INFO [2022-09-19 04:18:26] 3740682  Unexpected Error: Google\Service\Exception: {
  "error": {
    "code": 401,
    "message": "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
    "errors": [
      {
        "message": "Invalid Credentials",
        "domain": "global",
        "reason": "authError",
        "location": "Authorization",
        "locationType": "header"
      }
    ],
    "status": "UNAUTHENTICATED"
  }
}
 in /mnt/data/web-prod/fr.sudradio.matomo/plugins/GoogleAnalyticsImporter/vendor/google/apiclient/src/Http/REST.php:128
Stack trace:
#0 /mnt/data/web-prod/fr.sudradio.matomo/plugins/GoogleAnalyticsImporter/vendor/google/apiclient/src/Http/REST.php(103): Google\Http\REST::decodeHttpResponse()
#1 [internal function]: Google\Http\REST::doExecute()
#2 /mnt/data/web-prod/fr.sudradio.matomo/plugins/GoogleAnalyticsImporter/vendor/google/apiclient/src/Task/Runner.php(182): call_user_func_array()
#3 /mnt/data/web-prod/fr.sudradio.matomo/plugins/GoogleAnalyticsImporter/vendor/google/apiclient/src/Http/REST.php(66): Google\Task\Runner->run()
#4 /mnt/data/web-prod/fr.sudradio.matomo/plugins/GoogleAnalyticsImporter/vendor/google/apiclient/src/Client.php(922): Google\Http\REST::execute()
#5 /mnt/data/web-prod/fr.sudradio.matomo/plugins/GoogleAnalyticsImporter/vendor/google/apiclient/src/Service/Resource.php(238): Google\Client->execute()
#6 /mnt/data/web-prod/fr.sudradio.matomo/plugins/GoogleAnalyticsImporter/vendor/google/apiclient-services/src/AnalyticsReporting/Resource/Reports.php(44): Google\Service\Resource->call()
#7 /mnt/data/web-prod/fr.sudradio.matomo/plugins/GoogleAnalyticsImporter/Google/GoogleAnalyticsQueryService.php(161): Google\Service\AnalyticsReporting\Resource\Reports->batchGet()
#8 /mnt/data/web-prod/fr.sudradio.matomo/plugins/GoogleAnalyticsImporter/Google/GoogleAnalyticsQueryService.php(103): Piwik\Plugins\GoogleAnalyticsImporter\Google\GoogleAnalyticsQueryService->gaBatchGet()
#9 /mnt/data/web-prod/fr.sudradio.matomo/plugins/GoogleAnalyticsImporter/Importers/Actions/RecordImporter.php(474): Piwik\Plugins\GoogleAnalyticsImporter\Google\GoogleAnalyticsQueryService->query()
#10 /mnt/data/web-prod/fr.sudradio.matomo/plugins/GoogleAnalyticsImporter/Importers/Actions/RecordImporter.php(208): Piwik\Plugins\GoogleAnalyticsImporter\Importers\Actions\RecordImporter->queryExitPagesForUrls()
#11 /mnt/data/web-prod/fr.sudradio.matomo/plugins/GoogleAnalyticsImporter/Importers/Actions/RecordImporter.php(105): Piwik\Plugins\GoogleAnalyticsImporter\Importers\Actions\RecordImporter->queryExitPages()
#12 /mnt/data/web-prod/fr.sudradio.matomo/plugins/GoogleAnalyticsImporter/Importer.php(458): Piwik\Plugins\GoogleAnalyticsImporter\Importers\Actions\RecordImporter->importRecords()
#13 /mnt/data/web-prod/fr.sudradio.matomo/plugins/GoogleAnalyticsImporter/Importer.php(397): Piwik\Plugins\GoogleAnalyticsImporter\Importer->importDay()
#14 /mnt/data/web-prod/fr.sudradio.matomo/plugins/GoogleAnalyticsImporter/Commands/ImportReports.php(269): Piwik\Plugins\GoogleAnalyticsImporter\Importer->import()
#15 /mnt/data/web-prod/fr.sudradio.matomo/plugins/GoogleAnalyticsImporter/Commands/ImportReports.php(58): Piwik\Plugins\GoogleAnalyticsImporter\Commands\ImportReports->executeImpl()
#16 /mnt/data/web-prod/fr.sudradio.matomo/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Piwik\Plugins\GoogleAnalyticsImporter\Commands\ImportReports->execute()
#17 /mnt/data/web-prod/fr.sudradio.matomo/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run()
#18 /mnt/data/web-prod/fr.sudradio.matomo/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand()
#19 [internal function]: Symfony\Component\Console\Application->doRun()
#20 /mnt/data/web-prod/fr.sudradio.matomo/core/Console.php(135): call_user_func()
#21 /mnt/data/web-prod/fr.sudradio.matomo/core/Access.php(670): Piwik\Console->Piwik\{closure}()
#22 /mnt/data/web-prod/fr.sudradio.matomo/core/Console.php(136): Piwik\Access::doAsSuperUser()
#23 /mnt/data/web-prod/fr.sudradio.matomo/core/Console.php(87): Piwik\Console->doRunImpl()
#24 /mnt/data/web-prod/fr.sudradio.matomo/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Piwik\Console->doRun()
#25 /mnt/data/web-prod/fr.sudradio.matomo/console(32): Symfony\Component\Console\Application->run()
#26 {main}
Error encountered, aborting.
Running archiving for newly imported data...
INFO [2022-09-19 04:18:26] 3782417  ---------------------------
INFO [2022-09-19 04:18:26] 3782417  INIT
INFO [2022-09-19 04:18:26] 3782417  Running Matomo 4.11.0 as Super User
INFO [2022-09-19 04:18:26] 3782417  ---------------------------
INFO [2022-09-19 04:18:26] 3782417  NOTES
INFO [2022-09-19 04:18:26] 3782417  - Async process archiving supported, using CliMulti.
INFO [2022-09-19 04:18:26] 3782417  - Reports for today will be processed at most every 900 seconds. You can change this value in Matomo UI > Settings > General Settings.
INFO [2022-09-19 04:18:26] 3782417  - Archiving was last executed without error 13 min 0s ago.
INFO [2022-09-19 04:18:26] 3782417  - Will process 1 websites (--force-idsites)
INFO [2022-09-19 04:18:26] 3782417  - Will process specified sites: 6
INFO [2022-09-19 04:18:26] 3782417  - Will only process the following periods: week, month, year (--force-periods)
INFO [2022-09-19 04:18:26] 3782417  ---------------------------
INFO [2022-09-19 04:18:26] 3782417  START
INFO [2022-09-19 04:18:26] 3782417  Starting Matomo reports archiving...
INFO [2022-09-19 04:18:26] 3782417  Start processing archives for site 6.
INFO [2022-09-19 04:18:26] 3782417    Will invalidate archived reports for today in site ID = 6's timezone (2022-09-19 00:00:00).
INFO [2022-09-19 04:18:28] 3782417  Archived website id 6, period = week, date = 2022-06-06, segment = '', 81883 visits found. Time elapsed: 1.764s
INFO [2022-09-19 04:18:28] 3782417  Archived website id 6, period = week, date = 2022-05-30, segment = '', 83445 visits found. Time elapsed: 1.764s
INFO [2022-09-19 04:18:28] 3782417  Archived website id 6, period = week, date = 2022-05-23, segment = '', 83150 visits found. Time elapsed: 1.764s
INFO [2022-09-19 04:18:31] 3782417  Archived website id 6, period = month, date = 2022-06-01, segment = '', 394293 visits found. Time elapsed: 2.880s
INFO [2022-09-19 04:18:31] 3782417  Archived website id 6, period = week, date = 2022-05-16, segment = '', 87384 visits found. Time elapsed: 2.880s
INFO [2022-09-19 04:18:32] 3782417  Archived website id 6, period = month, date = 2022-05-01, segment = '', 196989 visits found. Time elapsed: 1.153s
INFO [2022-09-19 04:18:35] 3782417  Archived website id 6, period = year, date = 2022-01-01, segment = '', 1311370 visits found. Time elapsed: 2.732s
INFO [2022-09-19 04:18:35] 3782417  Finished archiving for site 6, 7 API requests, Time elapsed: 8.921s [1 / 1 done]
INFO [2022-09-19 04:18:35] 3782417  Done archiving!
INFO [2022-09-19 04:18:35] 3782417  ---------------------------
INFO [2022-09-19 04:18:35] 3782417  SUMMARY
INFO [2022-09-19 04:18:35] 3782417  Processed 7 archives.
INFO [2022-09-19 04:18:35] 3782417  Total API requests: 7
INFO [2022-09-19 04:18:35] 3782417  done: 7 req, 8924 ms, no error
INFO [2022-09-19 04:18:35] 3782417  Time elapsed: 8.924s
INFO [2022-09-19 04:18:35] 3782417  ---------------------------
INFO [2022-09-19 04:18:35] 3782417  SCHEDULED TASKS
INFO [2022-09-19 04:18:35] 3782417  Scheduled tasks are disabled with --disable-scheduled-tasks
Done in Time elapsed: 3563.942s. [5011 API requests made to GA]
Error: error or warning logs detected, exit 1

**Comment by pdechanoz** [comment]
And now when i trie to relaunch  with command line: 

  php ./console googleanalyticsimporter:import-reports  --idsite=6
Resuming import into existing site 6.
No dates specified with --dates, importing data from when the GA site was created to today: 2014-02-05
INFO [2022-09-19 04:50:22] 3806809  Using existing custom variable slots.
Importing the following date ranges in order: 2014-02-05,2022-09-18
(Entry #0) is finished, moving on.
Done in Time elapsed: 0.387s. [0 API requests made to GA]

**Comment by pdechanoz** [comment]
The file log 
[gaimportlog.6..log.zip](https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/files/9596232/gaimportlog.6.log.zip)

**Comment by AltamashShaikh** [comment]
@pdechanoz Do you have a google workspace account, or you have set the OAuth bt creating an `external` APP ?
If yes can you check this [doc](https://matomo.org/faq/general/set-up-google-analytics-import/) again and undo the scopes part and try to publish your App and post that you need to reauthorise via Matomo Admin.

**Comment by pdechanoz** [comment]
I haven't  a google workspace account. I have created the APP with your tutorial.

**Comment by AltamashShaikh** [comment]
> I haven't a google workspace account. I have created the APP with your tutorial.

@pdechanoz Is it published and when did you create a APP more that 7 days ago ?

**Comment by pdechanoz** [comment]
This APP is not publish, and it's created 14 september
PS : before launch the import i reautorise via Matomo Admin

**Comment by AltamashShaikh** [comment]
@pdechanoz So for external non published APP the authorisation expires in 7 days and you need to reauthorise again after 7 days, to ease this pain we have updated the [guide](https://matomo.org/faq/general/set-up-google-analytics-import/) which helps in publishing the external apps and published external app do not require authentication every 7 days and from the log file we can say its a authentication problem or permission issue can you also check step 6 and 7 are completed as mention in the guide ?

**Comment by pdechanoz** [comment]
Just a thing :

My APP is in production (not in test) but, not verification

Validation status
Validation not required

**Comment by AltamashShaikh** [comment]
@pdechanoz And `Analytics Reporting API` and `Google Analytics API` are enabled too correct ?

**Comment by pdechanoz** [comment]
It's seems
joint : img with utilisation
<img width="1237" alt="Notification_Center" src="https://user-images.githubusercontent.com/9005872/190974910-b5365197-a7cd-4e51-a67f-f01b52ac3cf4.png">

**Comment by AltamashShaikh** [comment]
@pdechanoz Thanks for all the info..last thing can you reauthorise the APP and re run a import and check the log file ?

**Comment by pdechanoz** [comment]
It's done.

No dates specified with --dates, importing data from when the GA site was created to today: 2014-02-05
INFO [2022-09-19 08:13:27] 3992837  Using existing custom variable slots.
Importing the following date ranges in order: 2014-02-05,2022-09-18
(Entry #0) is finished, moving on.
Done in Time elapsed: 0.475s. [0 API requests made to GA]

[gaimportlog.6..log.zip](https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/files/9597182/gaimportlog.6.log.zip)

**Comment by pdechanoz** [comment]
In fact, when i relance a NEW import it's work a few minutes...

But i can't relance an existant import

**Comment by AltamashShaikh** [comment]
@pdechanoz The log file still shows `UNAUTHENTICATED` error can you please check if its valid `OAuth` file you have uploaded and also which plugin and core version are you using ?
```
{"web":{"client_id":"xxxx,"project_id":"xx","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"xxxx","redirect_uris":["https://{YOUR_MATOMO_HOST}/index.php?module=GoogleAnalyticsImporter&action=processAuthCode"],"javascript_origins":["https://{YOUR_MATOMO_HOST}"]}}
```

**Comment by pdechanoz** [comment]
The json file
{"web":{"client_id":"xxxxxxxxxxxxxxapps.googleusercontent.com","project_id":"matomo-ga-3xxx","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"GOCSPX-xxxxxxxxxxxxxxxxx","redirect_uris":["https://matomo.sudradio.fr/index.php?module=GoogleAnalyticsImporter&action=processAuthCode"],"javascript_origins":["https://matomo.sudradio.fr"]}}

[GoogleAnalyticsImporter] : (v4.3.2)

![Screenshot 2022-09-19 at 11-39-59 Vérification du système - Administration - Matomo](https://user-images.githubusercontent.com/9005872/190991241-76ade6c2-5088-4905-b941-b8b7b65ededb.png)

**Comment by pdechanoz** [comment]
I have created a new APP on Google  cloud, and started a new import, but i have always the same problem.
[gaimportlog.7..log.zip](https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/files/9604045/gaimportlog.7.log.zip)

**Comment by justinvelluppillai** [comment]
@samjf do you possibly have any insights here?

**Comment by pdechanoz** [comment]
In resume : 
- I can launch a new import, and this import work a  time. => the Oauth2 connection work
- When the import crash, i can't relaunch them
- if i launch a new import it's work a time ....
- Why the import can't be relaunched ?

 I just want to be able to restart the current import

**Comment by pdechanoz** [comment]
import restarted automatically :

INFO [2022-09-20 04:11:28] 689872  Total API requests: 3
INFO [2022-09-20 04:11:28] 689872  done: 3 req, 5476 ms, no error
INFO [2022-09-20 04:11:28] 689872  Time elapsed: 5.476s
INFO [2022-09-20 04:11:28] 689872  ---------------------------
INFO [2022-09-20 04:11:28] 689872  SCHEDULED TASKS
INFO [2022-09-20 04:11:28] 689872  Scheduled tasks are disabled with --disable-scheduled-tasks
Done in Time elapsed: 3542.396s. [3981 API requests made to GA]
Error: error or warning logs detected, exit 1
Import for site with ID = 7 has errored, will attempt to resume.
No dates specified with --dates, importing data from when the GA site was created to today: 2014-02-05
INFO [2022-09-20 05:05:15] 723239  Using existing custom variable slots.
Importing the following date ranges in order: 2014-02-05,2022-09-19
Importing reports for date range 2022-06-14 - 2022-09-19 from GA view 81857407.
INFO [2022-09-20 05:05:16] 723239  Importing data for GA View 81857407 for date 2022-09-19...
WARNING [2022-09-20 05:05:19] 723239  Encountered unknown search engine source from Google Analytics: qwant.com
WARNING [2022-09-20 05:05:19] 723239  Encountered unknown search engine source from Google Analytics: ecosia.org
WARNING [2022-09-20 05:05:34] 723239  Encountered unknown device brand: Mozilla. A new mapping should be added.
WARNING [2022-09-20 05:05:34] 723239  Encountered unknown device brand: Honor. A new mapping should be added.
WARNING [2022-09-20 05:05:34] 723239  Encountered unknown device brand: Dynamic. A new mapping should be added.
WARNIN

**Comment by pdechanoz** [comment]
the import is stopped again, without problem Oauth
[gaimportlog.7..log.zip](https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/files/9604480/gaimportlog.7.log.zip)

WARNING [2022-09-20 05:37:14] 723239  Encountered unknown browser: YaBrowser. A new mapping should be added.
WARNING [2022-09-20 05:37:14] 723239  Encountered unknown browser: YaBrowser. A new mapping should be added.
Running archiving for newly imported data...
INFO [2022-09-20 05:37:18] 723239  Last archived date (2022-06-14) is earlier than last import date (2022-06-13, no need to archive for site ID = 7
Done in Time elapsed: 1923.351s. [3920 API requests made to GA]
Error: error or warning logs detected, exit 1

**Comment by pdechanoz** [comment]
... but i can restart it

**Comment by pdechanoz** [comment]
2 days ago the import stop "_Daily rate limit reached, try again tomorrow..._" It's normal.

But since 2 days i have always this message. The import don't relaunch
 
The log : [Archive.zip](https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/files/9622235/Archive.zip)

What can I do ?

**Comment by samjf** [comment]
This message is expected over a 24 hour period until the next day. Since it is being resumed almost each hour according to the logs, then you are getting a lot of daily limit reached messages.

It is clear if you run `grep 'Importing data for GA View' ~/Downloads/Archive/gaimportlog.7..log` that the importer is making progress before meeting its daily limit from Google. You can check your quota usage on the Google console.

Potentially for the error `Request had invalid authentication credentials.` it might be due to the renewal token expiring/revoking/not being issued(?). I believe if it gets in this state you could try removing the OAuth app from your Google account at https://myaccount.google.com/security before retrying to re-authenticate on the Importer page.

**Comment by pdechanoz** [comment]
I deleted the access in google.com/security, I re-authenticated myself, and I relaunched the application, but the problem is the same :

INFO [2022-09-23 04:10:46] 3796436  Using existing custom variable slots.
Importing the following date ranges in order: 2014-02-05,2022-09-22
Importing reports for date range 2022-06-14 - 2022-09-22 from GA view 81857407.
INFO [2022-09-23 04:10:46] 3796436  Importing data for GA View 81857407 for date 2022-09-22...
INFO [2022-09-23 04:10:47] 3796436  Daily rate limit reached, try again tomorrow. (Note: GA by default sets a daily limit on the number of API requests made each day to 50000. It looks like you've reached this limit. Continue the import tomorrow.)
Error encountered, aborting.
Running archiving for newly imported data...
INFO [2022-09-23 04:10:47] 3796436  Last archived date (2022-06-14) is earlier than last import date (2022-06-13, no need to archive for site ID = 7
Done in Time elapsed: 0.738s. [0 API requests made to GA]

**Comment by pdechanoz** [comment]
My quota :
<img width="1477" alt="image" src="https://user-images.githubusercontent.com/9005872/191891458-e2fea69a-54c7-4186-a610-33cea26e726d.png">

**Comment by AltamashShaikh** [comment]
@pdechanoz - Refer this #243 to better understand why are you hitting the limits

**Comment by samjf** [comment]
@pdechanoz I believe you have in fact reached your Google quota for the _view_ potentially. Google has a project quota of `50_000` per day. But also a profile/view quota of `10_000` per day. See here: https://developers.google.com/analytics/devguides/reporting/core/v3/limits-quotas

![image](https://user-images.githubusercontent.com/8619576/191893826-47758f75-0d23-44c0-b84b-aad580c2cb98.png)

Just realised your link explains this @AltamashShaikh 🤦 Haha

**Comment by pdechanoz** [comment]
he problem is that the quotas are not reset from one day to the next. Today I haven't used anything yet :

<img width="961" alt="image" src="https://user-images.githubusercontent.com/9005872/191895499-27c0bf5f-4fc7-45fd-b14a-89b659a3c005.png">

**Comment by pdechanoz** [comment]
Since I started the import on Sept 20, it goes until June 14 and restarts the import from the day before, and so on :
[Archive 2.zip](https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/files/9662157/Archive.2.zip)

INFO [2022-09-27 08:01:03] 3053363  Importing data for GA View 81857407 for date 2022-06-19...
INFO [2022-09-27 08:01:31] 3053363  Importing data for GA View 81857407 for date 2022-06-18...
INFO [2022-09-27 08:01:57] 3053363  Importing data for GA View 81857407 for date 2022-06-17...
INFO [2022-09-27 08:02:24] 3053363  Importing data for GA View 81857407 for date 2022-06-16...
INFO [2022-09-27 08:02:53] 3053363  Importing data for GA View 81857407 for date 2022-06-15...
**INFO [2022-09-27 08:03:39] 3053363  Importing data for GA View 81857407 for date 2022-06-14...
INFO [2022-09-27 08:05:29] 3101277  Importing data for GA View 81857407 for date 2022-09-26...**
INFO [2022-09-27 08:05:51] 3101277  Importing data for GA View 81857407 for date 2022-09-25...
INFO [2022-09-27 08:06:09] 3101277  Importing data for GA View 81857407 for date 2022-09-24...
INFO [2022-09-27 08:06:30] 3101277  Importing data for GA View 81857407 for date 2022-09-23...
INFO [2022-09-27 08:06:49] 3101277  Importing data for GA View 81857407 for date 2022-09-22...
INFO [2022-09-27 08:07:09] 3101277  Importing data for GA View 81857407 for date 2022-09-21...

**Comment by AltamashShaikh** [comment]
@pdechanoz Does applying fixes of this branch https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/pull/281 fixes the issue?

**Comment by pdechanoz** [comment]
Excuse me, but what should I do to apply the patch?
a git clone of the plugin?

**Comment by AltamashShaikh** [comment]
Hey @pdechanoz you have to update ‘ Commands/ImportReports.php’ the file with this file 
https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/blob/6492069a83e587788dabbc73e13977cf91ee6a97/Commands/ImportReports.php

**Comment by AltamashShaikh** [comment]
@pdechanoz if you are importing any GA4 property please update this Commands/ImportGA4Reports.php file with
https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/blob/6492069a83e587788dabbc73e13977cf91ee6a97/Commands/ImportGA4Reports.php

**Comment by pdechanoz** [comment]
it works, but it jumped on 2022/06/13

INFO [2022-09-28 07:54:11] 4083348  Importing data for GA View 81857407 for date 2022-06-16...
INFO [2022-09-28 07:54:38] 4083348  Importing data for GA View 81857407 for date 2022-06-15...
**INFO [2022-09-28 07:55:07] 4083348  Importing data for GA View 81857407 for date 2022-06-14...
INFO [2022-09-28 08:05:25] 4129947  Importing data for GA View 81857407 for date 2022-06-12...**
INFO [2022-09-28 08:05:49] 4129947  Importing data for GA View 81857407 for date 2022-06-11...
INFO [2022-09-28 08:06:19] 4129947  Importing data for GA View 81857407 for date 2022-06-10...
INFO [2022-09-28 08:06:45] 4129947  Importing data for GA View 81857407 for date 2022-06-09...
INFO [2022-09-28 08:07:11] 4129947  Importing data for GA View 81857407 for date 2022-06-08...
INFO [2022-09-28 08:07:35] 4129947  Importing data for GA View 81857407 for date 2022-06-07...
INFO [2022-09-28 08:07:58] 4129947  Importing data for GA View 81857407 for date 2022-06-06...
IN

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/google-analytics-import-process-gets-killed-after-1-day/47546/5
